name: facefilter
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1  # remove this line if you don't have NVIDIA GPU

  - pip:
      - ultralytics
      - mediapipe
      - opencv-python
